### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by Ghaiyur** [edebrouwer/gru_ode_bayes#4]
The referenced files folds_split_mimic.py and mimic_prepoc.py are missing from the repo

**Comment by exowanderer** [comment]
Same issue here with `double_OU_gru_ode_bayes_demo_params.npy`.

----
### Traceback
```python
Demo Mode - Loading model for double_OU ....
Traceback (most recent call last):
  File "double_ou_gruode.py", line 25, in <module>
    gru_ode_bayes.paper_plotting.plot_trained_model(model_name = "double_OU_gru_ode_bayes_demo")
  File "$HOME/github/gru_ode_bayes/gru_ode_bayes/paper_plotting.py", line 25, in plot_trained_model
    summary_dict=np.load(f"./../trained_models/{model_name}_params.npy",allow_pickle=True).item()
  File "$HOME/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './../trained_models/double_OU_gru_ode_bayes_demo_params.npy'
```

**Comment by tql247** [comment]
Same...
When I run python process.py in /data_preproc/Climate folder
```
Traceback (most recent call last):
  File "process.py", line 231, in <module>
    clean_and_subsample()
  File "process.py", line 87, in clean_and_subsample
    df =  pd.read_csv("daily_merged.csv")
  File "/home/lian/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/lian/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/lian/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/lian/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/home/lian/.local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] File daily_merged.csv does not exist: 'daily_merged.csv'
```
I get ushcn data from [ftp://ftp.ncdc.noaa.gov/pub/data/ushcn/daily/](url). I hope someone could tell me why daily_merged.csv is missing....

**Comment by matthewvowels1** [comment]
> Same issue here with `double_OU_gru_ode_bayes_demo_params.npy`.
> 
> ### Traceback
> ```python
> Demo Mode - Loading model for double_OU ....
> Traceback (most recent call last):
>   File "double_ou_gruode.py", line 25, in <module>
>     gru_ode_bayes.paper_plotting.plot_trained_model(model_name = "double_OU_gru_ode_bayes_demo")
>   File "$HOME/github/gru_ode_bayes/gru_ode_bayes/paper_plotting.py", line 25, in plot_trained_model
>     summary_dict=np.load(f"./../trained_models/{model_name}_params.npy",allow_pickle=True).item()
>   File "$HOME/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
>     fid = open(os_fspath(file), "rb")
> FileNotFoundError: [Errno 2] No such file or directory: './../trained_models/double_OU_gru_ode_bayes_demo_params.npy'
> ```

This can be quickly solved by running double_OU.py which generates the metadata file

**Comment by HoJ-Onle** [comment]
> Same issue here with `double_OU_gru_ode_bayes_demo_params.npy`.
> 
> ### Traceback
> ```python
> Demo Mode - Loading model for double_OU ....
> Traceback (most recent call last):
>   File "double_ou_gruode.py", line 25, in <module>
>     gru_ode_bayes.paper_plotting.plot_trained_model(model_name = "double_OU_gru_ode_bayes_demo")
>   File "$HOME/github/gru_ode_bayes/gru_ode_bayes/paper_plotting.py", line 25, in plot_trained_model
>     summary_dict=np.load(f"./../trained_models/{model_name}_params.npy",allow_pickle=True).item()
>   File "$HOME/anaconda3/envs/pytorch/lib/python3.8/site-packages/numpy/lib/npyio.py", line 428, in load
>     fid = open(os_fspath(file), "rb")
> FileNotFoundError: [Errno 2] No such file or directory: './../trained_models/double_OU_gru_ode_bayes_demo_params.npy'
> ```

I think maybe you should create a folder "trained_models" at first.
